version: "3.8"

services:
  streamlit-app:
    build: .
    container_name: streamlit-app
    volumes:
      - .:/app   # use current folder since compose is already in frontend/
    ports:
      - "8501:8501"
    restart: unless-stopped
